### ISSUE TITLE
NullPointerException when calling `PaymentOperationresponse.getAsset()`

### ISSUE THREAD

**Issue by lijamie98** [stellar/java-stellar-sdk#545] opened 2023-09-22 16:38 UTC
### What did you do?
[`PaymentOperationResponse.getAsset()`](https://github.com/stellar/java-stellar-sdk/blob/master/src/main/java/org/stellar/sdk/responses/operations/PaymentOperationResponse.java#L56) throws NPE when assetType is defined.

Here is the content of the `PaymentOperationResponse` that causes the NPE.

```json
{
  "amount": "15.0000000",
  "from": "testFrom",
  "to": "testTo",
  "id": 12345,
  "type": "payment",
  "transaction": {
    "hash": "testTxHash",
    "ledger": 1234,
    "successful": true,
    "signatures": [
      "testSignature1"
    ],
    "preconditions": {
      "min_account_sequence_age": 0,
      "min_account_sequence_ledger_gap": 0
    },
    "rateLimitLimit": 0,
    "rateLimitRemaining": 0,
    "rateLimitReset": 0
  },
  "rateLimitLimit": 0,
  "rateLimitRemaining": 0,
  "rateLimitReset": 0
}
```

### What did you expect to see?
`null`

### What did you see instead?
NPE

**Comment by overcat** [comment] 2023-09-22 16:47
Hi, is this a valid Response? If I remember correctly, `asset_type` must exist, but it is not present in the example you provided. Do you mind providing the transaction hash?

**Comment by overcat** [comment] 2023-10-20 08:56
Based on the above discussion, I believe this is not a bug, I have decided to close it. If there are any more problems, please don't hesitate to reopen it.

**Closed by overcat** 2023-10-20 08:56 UTC
Labels: bug
