### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by EV6999** [stellar/java-stellar-sdk#403] opened 2022-01-13 17:51 UTC
### What version are you using?
0.31.0

### What did you do?
There is no null check for liquidityPoolID. 
When liquidityPoolID is null, liquidityPoolID.toString() causes an error.

https://github.com/stellar/java-stellar-sdk/blob/24426ee0256b330aa4bc0d5d361bd161f[…]e9/src/main/java/org/stellar/sdk/responses/AccountResponse.java

**Comment by vinamogit** [comment] 2022-04-30 21:17
Duplicate of #405

**Closed** 2022-06-01 22:36 UTC
Labels: bug
