### ISSUE TITLE
Not a JSON Object: "problem"

### ISSUE THREAD

**Issue by lijianl** [stellar/java-stellar-sdk#408] opened 2022-02-16 08:11 UTC
version 0.31.0

```java
07:44:57.547    [OkHttp https://horizon.stellar.org/...] ERROR com.novadax.coin.xlm.WalletXLMServiceImpl -xlm-failure->>{}
shadow.com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: "problem"
	at shadow.com.google.gson.Gson.fromJson(Gson.java:939)
	at shadow.com.google.gson.Gson.fromJson(Gson.java:892)
	at shadow.com.google.gson.Gson.fromJson(Gson.java:841)
	at shadow.com.google.gson.Gson.fromJson(Gson.java:813)
	at org.stellar.sdk.requests.SSEStream$StellarEventSourceListener.onEvent(SSEStream.java:202)
	at shadow.okhttp3.internal.sse.RealEventSource.onEvent(RealEventSource.java:111)
	at shadow.okhttp3.internal.sse.ServerSentEventReader.completeEvent(ServerSentEventReader.java:112)
	at shadow.okhttp3.internal.sse.ServerSentEventReader.processNextEvent(ServerSentEventReader.java:69)
	at shadow.okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.java:80)
	at shadow.okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.java:54)
	at shadow.okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at shadow.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Not a JSON Object: "problem"
	at shadow.com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
	at org.stellar.sdk.responses.OperationDeserializer.deserialize(OperationDeserializer.java:34)
	at org.stellar.sdk.responses.OperationDeserializer.deserialize(OperationDeserializer.java:20)
	at shadow.com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at shadow.com.google.gson.Gson.fromJson(Gson.java:927)
	... 14 common frames omitted
```

how to solve this

this bug was threw from java sdk, and happens frequently

**Comment by lijianl** [comment] 2022-02-16 08:14
question 2:
public void onFailure the bug upon,  the stream will stop listening..

**Comment by StanislavKozlovsky** [comment] 2022-11-07 11:26
Same issue

**Comment by overcat** [comment] 2023-11-07 09:14
Let's track it [here](https://github.com/stellar/java-stellar-sdk/issues/463) for the second question.

**Comment by overcat** [comment] 2023-11-07 12:08
Due to the lack of sufficient debug information (such as transaction hash), and I am unable to reproduce it either, so I have decided to close it. If there are any further issues later on, feel free to reopen it.

**Closed by overcat** 2023-11-07 12:08 UTC
Labels: bug
